### ISSUE TITLE
Orb Review

### ISSUE THREAD

**Issue by brivu** [kobiton/kobiton-circleci-orb#2]
Hey Kobiton Team!

My name is Brian from CircleCI's Customer and Partner Engineering Team.  I just reviewed your orb and would like to suggest the following revisions:

- Currently in your `config.yml` file, you do not have any tests for your jobs or commands.  These tests are added under the `integration-test_deploy` section of your workflow.  The GitHub CLI Orb is a really simple and great example.  I've linked it [here](https://github.com/CircleCI-Public/github-cli-orb/blob/66c645413222b055ba90c31f2b73bbb6284dc6a0/.circleci/config.yml#L104)

- In each of your commands, you are exporting each parameter to an environment variable.  This creates an extra step.  To simplify this, we recommend using the environment parameter and expanding this in your bash script.  For example: 

```
steps:
  - checkout
  - run:
      name: Export values
      environment:
          PARAM_KOBI_USERNAME: <<parameters.KOBITON_USERNAME>>
          PARAM_OTHER_VARS: <<parameters.OTHER_VARS>>>
      command: <<include(scripts/test.sh)>>
```
And then in your script, you can expand the variables by doing the following: 
```
KOBI_USERNAME=$"(eval echo "$PARAM_KOBI_USERNAME")"
```
Again, a good example of this can be seen [here](https://github.com/CircleCI-Public/github-cli-orb/blob/66c645413222b055ba90c31f2b73bbb6284dc6a0/src/commands/clone.yml#L18) and [here](https://github.com/CircleCI-Public/github-cli-orb/blob/66c645413222b055ba90c31f2b73bbb6284dc6a0/src/scripts/clone.sh#L4)

- The `wget` in your commands should download a versioned file.  Orbs by nature should be immutable and predictable but the `wget` is downloading from `master` in your GitHub repo, which can change at any time.  This may cause sudden and breaking changes for customers using your orb for their builds.  

- Update your Orb description - The description of your orb is searchable in our orb registry so you may want to consider adding a little bit more information about your product and what your orb does.  

- Remove all the unnecessary `README.md` files.

- Remove executor directory and the `default` executor from both of your jobs entirely.  

- Remove all unnecessary comments in your scripts and `yml` files

Please make these changes and ping me if you have any questions! 

Best, 
Brian
